# -*- coding: utf-8 -*-
"""day 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_NY28VKZLqrHCRj135bdDxrzYitxt7bS
"""

import cv2

import numpy as np

import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
img=cv2.imread("/content/sample.jpeg")
cv2_imshow(img)

gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2_imshow(hsv)

hist=cv2.calcHist(gray,[0],None,[256],[0,256])
plt.plot(hist)
plt.show()
histeq=cv2.equalizeHist(gray)
plt.plot(histeq)
plt.show()
cv2_imshow(histeq)

b,g,r=cv2.split(img)
plt.subplot(1,3,1)
plt.hist(b.ravel(),256,[0,256])
plt.title("Blue")
plt.xlabel("Intensity")
plt.ylabel("Freq")

plt.subplot(1,3,2)
plt.hist(g.ravel(),256,[0,256])
plt.title("Green")
plt.xlabel("Intensity")
plt.ylabel("Freq")

plt.subplot(1,3,3)
plt.hist(r.ravel(),256,[0,256])
plt.title("Red")
plt.xlabel("Intensity")
plt.ylabel("Freq")

import cv2
import numpy as np
import matplotlib.pyplot as plt
img=cv2.imread("/content/sample.jpeg")
cv2_imshow(img)
arr=np.array(img)
print(arr)